// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Entrenamiento struct {
	ID          int32          `json:"id"`
	Fecha       time.Time      `json:"fecha"`
	DistanciaKm float64        `json:"distancia_km"`
	TiempoMin   int32          `json:"tiempo_min"`
	Tipo        string         `json:"tipo"`
	ZapatillaID int32          `json:"zapatilla_id"`
	Ritmo       float64        `json:"ritmo"`
	Calorias    int32          `json:"calorias"`
	Lugar       sql.NullString `json:"lugar"`
}

type Zapatilla struct {
	ID            int32   `json:"id"`
	MarcaModelo   string  `json:"marca_modelo"`
	KmsAcumulados float64 `json:"kms_acumulados"`
	Estado        bool    `json:"estado"`
}
