// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createEntrenamiento = `-- name: CreateEntrenamiento :one
INSERT INTO entrenamientos (fecha, distancia_km, tiempo_min, tipo, zapatilla_id, ritmo, calorias, lugar) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) 
RETURNING id, fecha, distancia_km, tiempo_min, tipo, zapatilla_id, ritmo, calorias, lugar
`

type CreateEntrenamientoParams struct {
	Fecha       time.Time      `json:"fecha"`
	DistanciaKm float64        `json:"distancia_km"`
	TiempoMin   int32          `json:"tiempo_min"`
	Tipo        string         `json:"tipo"`
	ZapatillaID int32          `json:"zapatilla_id"`
	Ritmo       float64        `json:"ritmo"`
	Calorias    int32          `json:"calorias"`
	Lugar       sql.NullString `json:"lugar"`
}

func (q *Queries) CreateEntrenamiento(ctx context.Context, arg CreateEntrenamientoParams) (Entrenamiento, error) {
	row := q.db.QueryRowContext(ctx, createEntrenamiento,
		arg.Fecha,
		arg.DistanciaKm,
		arg.TiempoMin,
		arg.Tipo,
		arg.ZapatillaID,
		arg.Ritmo,
		arg.Calorias,
		arg.Lugar,
	)
	var i Entrenamiento
	err := row.Scan(
		&i.ID,
		&i.Fecha,
		&i.DistanciaKm,
		&i.TiempoMin,
		&i.Tipo,
		&i.ZapatillaID,
		&i.Ritmo,
		&i.Calorias,
		&i.Lugar,
	)
	return i, err
}

const createZapatilla = `-- name: CreateZapatilla :one
INSERT INTO zapatillas (marca_modelo, kms_acumulados, estado) 
VALUES ($1, $2, $3) 
RETURNING id, marca_modelo, kms_acumulados, estado
`

type CreateZapatillaParams struct {
	MarcaModelo   string  `json:"marca_modelo"`
	KmsAcumulados float64 `json:"kms_acumulados"`
	Estado        bool    `json:"estado"`
}

func (q *Queries) CreateZapatilla(ctx context.Context, arg CreateZapatillaParams) (Zapatilla, error) {
	row := q.db.QueryRowContext(ctx, createZapatilla, arg.MarcaModelo, arg.KmsAcumulados, arg.Estado)
	var i Zapatilla
	err := row.Scan(
		&i.ID,
		&i.MarcaModelo,
		&i.KmsAcumulados,
		&i.Estado,
	)
	return i, err
}

const deleteEntrenamiento = `-- name: DeleteEntrenamiento :exec
DELETE FROM entrenamientos WHERE id = $1
`

func (q *Queries) DeleteEntrenamiento(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEntrenamiento, id)
	return err
}

const getEntrenamiento = `-- name: GetEntrenamiento :one
SELECT id, fecha, distancia_km, tiempo_min, tipo, zapatilla_id, ritmo, calorias, lugar FROM entrenamientos WHERE id = $1
`

func (q *Queries) GetEntrenamiento(ctx context.Context, id int32) (Entrenamiento, error) {
	row := q.db.QueryRowContext(ctx, getEntrenamiento, id)
	var i Entrenamiento
	err := row.Scan(
		&i.ID,
		&i.Fecha,
		&i.DistanciaKm,
		&i.TiempoMin,
		&i.Tipo,
		&i.ZapatillaID,
		&i.Ritmo,
		&i.Calorias,
		&i.Lugar,
	)
	return i, err
}

const listEntrenamientos = `-- name: ListEntrenamientos :many
SELECT id, fecha, distancia_km, tiempo_min, tipo, zapatilla_id, ritmo, calorias, lugar FROM entrenamientos ORDER BY fecha DESC
`

func (q *Queries) ListEntrenamientos(ctx context.Context) ([]Entrenamiento, error) {
	rows, err := q.db.QueryContext(ctx, listEntrenamientos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entrenamiento
	for rows.Next() {
		var i Entrenamiento
		if err := rows.Scan(
			&i.ID,
			&i.Fecha,
			&i.DistanciaKm,
			&i.TiempoMin,
			&i.Tipo,
			&i.ZapatillaID,
			&i.Ritmo,
			&i.Calorias,
			&i.Lugar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZapatillas = `-- name: ListZapatillas :many
SELECT id, marca_modelo, kms_acumulados, estado FROM zapatillas ORDER BY id
`

func (q *Queries) ListZapatillas(ctx context.Context) ([]Zapatilla, error) {
	rows, err := q.db.QueryContext(ctx, listZapatillas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zapatilla
	for rows.Next() {
		var i Zapatilla
		if err := rows.Scan(
			&i.ID,
			&i.MarcaModelo,
			&i.KmsAcumulados,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZapatillaKms = `-- name: UpdateZapatillaKms :exec
UPDATE zapatillas 
SET kms_acumulados = kms_acumulados + $2 
WHERE id = $1
`

type UpdateZapatillaKmsParams struct {
	ID            int32   `json:"id"`
	KmsAcumulados float64 `json:"kms_acumulados"`
}

func (q *Queries) UpdateZapatillaKms(ctx context.Context, arg UpdateZapatillaKmsParams) error {
	_, err := q.db.ExecContext(ctx, updateZapatillaKms, arg.ID, arg.KmsAcumulados)
	return err
}
